[package]
name = "tento-server"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.12.1"
bson = "3.1.0"
juniper = "0.17.1"
mongodb = "3.5.1"
serde = "1.0.228"
serde_json = "1.0"

[dev-dependencies]
actix-rt = "2.10"
tokio = { version = "1", features = ["macros"] }
